-- Northstar Triage Demo — initial schema.
-- Four tables only: referrals, triage_runs, workflow_events, app_config.
-- IDs are generated by the application (crypto.randomUUID()), not the database,
-- so this schema has no extension dependency.

create table referrals (
  id text primary key,
  source text not null,
  raw_text text not null,
  received_at timestamptz not null,
  service_requested text,
  status text not null default 'New'
    check (status in ('New', 'Needs Information', 'Ready to Schedule', 'Scheduled', 'Closed', 'Declined')),
  priority text
    check (priority is null or priority in ('Critical', 'Today', 'This Week', 'Needs Information', 'Manual Review')),
  owner_role text
    check (owner_role is null or owner_role in ('Triage Lead', 'Triage Nurse', 'Scheduling', 'Intake')),
  due_at timestamptz,
  completeness text
    check (completeness is null or completeness in ('complete', 'incomplete')),
  missing_fields text[] not null default '{}',
  current_triage_run_id uuid,
  is_synthetic boolean not null default true
);

create table triage_runs (
  id uuid primary key,
  referral_id text not null references referrals (id) on delete cascade,
  created_at timestamptz not null default now(),
  model text,
  prompt_version text,
  rules_version text,
  extracted_json jsonb,
  evidence_json jsonb,
  confidence numeric,
  rule_hits jsonb,
  final_priority text,
  final_route text
);

create table workflow_events (
  id uuid primary key,
  referral_id text not null references referrals (id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null,
  from_value text,
  to_value text,
  note text
);

create table app_config (
  key text primary key,
  value_json jsonb not null,
  updated_at timestamptz not null default now()
);

-- Added after triage_runs exists to avoid a circular forward reference.
alter table referrals
  add constraint referrals_current_triage_run_id_fkey
  foreign key (current_triage_run_id) references triage_runs (id) on delete set null;

create index referrals_status_idx on referrals (status);
create index referrals_priority_idx on referrals (priority);
create index triage_runs_referral_id_idx on triage_runs (referral_id);
create index workflow_events_referral_id_idx on workflow_events (referral_id);
